In [1]:
import spacy
import pandas as pd


In [2]:
df = pd.read_csv("C:\\Users\\Kshit\\Desktop\\NLP\\Alldata.csv", encoding='ISO-8859-1')
df.head()

neutral   
0   neutral  \
1  negative   
2  positive   
3  positive   
4  positive   

  According to Gran , the company has no plans to move all production to Russia , although that is where the company is growing .  
0  Technopolis plans to develop in stages an area...                                                                               
1  The international electronic industry company ...                                                                               
2  With the new production plant the company woul...                                                                               
3  According to the company 's updated strategy f...                                                                               
4  FINANCING OF ASPOCOMP 'S GROWTH Aspocomp is ag...

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4845 entries, 0 to 4844
Data columns (total 2 columns):
 #   Column                                                                                                                           Non-Null Count  Dtype 
---  ------                                                                                                                           --------------  ----- 
 0   neutral                                                                                                                          4845 non-null   object
 1   According to Gran , the company has no plans to move all production to Russia , although that is where the company is growing .  4845 non-null   object
dtypes: object(2)
memory usage: 75.8+ KB


In [4]:
newcolumnname = ['Feedback','Text']
df.columns = newcolumnname
df.head()


Feedback                                               Text
0   neutral  Technopolis plans to develop in stages an area...
1  negative  The international electronic industry company ...
2  positive  With the new production plant the company woul...
3  positive  According to the company 's updated strategy f...
4  positive  FINANCING OF ASPOCOMP 'S GROWTH Aspocomp is ag...

In [5]:
number = {'neutral':'2', 'positive':'3','negative':'1'}
df['Feedback'] = df['Feedback'].map(number)
df.head()

Feedback                                               Text
0        2  Technopolis plans to develop in stages an area...
1        1  The international electronic industry company ...
2        3  With the new production plant the company woul...
3        3  According to the company 's updated strategy f...
4        3  FINANCING OF ASPOCOMP 'S GROWTH Aspocomp is ag...

In [6]:
df['Feedback'].value_counts()

Feedback
2    2878
3    1363
1     604
Name: count, dtype: int64

Removing common words and punctuations(Stopwords) 

In [7]:
nlp = spacy.load("en_core_web_sm")
import string

In [8]:
def remove_stopwords_and_punctuation(text):
    doc = nlp(text)
    filtered_text = [token.text for token in doc if not (token.is_stop or token.text in string.punctuation)]
    return ' '.join(filtered_text)

In [9]:
df['Text'] = df['Text'].apply(remove_stopwords_and_punctuation)

In [10]:
print(df)

     Feedback                                               Text
0           2  Technopolis plans develop stages area 100,000 ...
1           1  international electronic industry company Elco...
2           3  new production plant company increase capacity...
3           3  According company updated strategy years 2009 ...
4           3  FINANCING ASPOCOMP GROWTH Aspocomp aggressivel...
...       ...                                                ...
4840        1  LONDON MarketWatch -- Share prices ended lower...
4841        2  Rinkuskiai beer sales fell 6.5 cent 4.16 milli...
4842        1  Operating profit fell EUR 35.4 mn EUR 68.8 mn ...
4843        1  Net sales Paper segment decreased EUR 221.6 mn...
4844        1  Sales Finland decreased 10.5 January sales out...

[4845 rows x 2 columns]


Applying TF-IDF Transformation

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [12]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_vectorizer.fit(df['Text'])

TfidfVectorizer()

In [13]:
tfidf_matrix = tfidf_vectorizer.transform(df['Text'])
print(tfidf_matrix)

  (0, 9668)	0.24486418305612523
  (0, 8773)	0.24679939858980152
  (0, 8748)	0.2509957673233442
  (0, 8744)	0.234965590927438
  (0, 8358)	0.2532830392028999
  (0, 8334)	0.28447232496209707
  (0, 8314)	0.24126827948476917
  (0, 7703)	0.12016969832763917
  (0, 6701)	0.21966802844985409
  (0, 6299)	0.18688059373751326
  (0, 5715)	0.28447232496209707
  (0, 4352)	0.31643954408206804
  (0, 2686)	0.2509957673233442
  (0, 2207)	0.2674196352703532
  (0, 2149)	0.17726390900737332
  (0, 1139)	0.20098032763173188
  (0, 49)	0.21426905810095742
  (0, 1)	0.16346285443076208
  (1, 9663)	0.2233898637375107
  (1, 8799)	0.2764349524375878
  (1, 8673)	0.22566378369392792
  (1, 7411)	0.18117186394607845
  (1, 7150)	0.2897985823472719
  (1, 6812)	0.2897985823472719
  (1, 6211)	0.18437426126463097
  :	:
  (4843, 7610)	0.15109031615947846
  (4843, 7250)	0.19018213090241673
  (4843, 7091)	0.2532770029867279
  (4843, 6953)	0.10807702086932947
  (4843, 6442)	0.16106494820693448
  (4843, 6266)	0.11808056308218405


Applying S.M.O.T.E

In [14]:
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf_vectorizer.get_feature_names_out())

# Concatenate the original DataFrame with the TF-IDF DataFrame
df = pd.concat([df, tfidf_df], axis=1)


In [15]:
print(df)

     Feedback                                               Text   00   
0           2  Technopolis plans develop stages area 100,000 ...  0.0  \
1           1  international electronic industry company Elco...  0.0   
2           3  new production plant company increase capacity...  0.0   
3           3  According company updated strategy years 2009 ...  0.0   
4           3  FINANCING ASPOCOMP GROWTH Aspocomp aggressivel...  0.0   
...       ...                                                ...  ...   
4840        1  LONDON MarketWatch -- Share prices ended lower...  0.0   
4841        2  Rinkuskiai beer sales fell 6.5 cent 4.16 milli...  0.0   
4842        1  Operating profit fell EUR 35.4 mn EUR 68.8 mn ...  0.0   
4843        1  Net sales Paper segment decreased EUR 221.6 mn...  0.0   
4844        1  Sales Finland decreased 10.5 January sales out...  0.0   

           000  000063  002  0025  003  0030  007  ...  ænnen  ænsi  ærnits   
0     0.163463     0.0  0.0   0.0  0.0   0.0

In [16]:
import numpy as np

In [17]:
from imblearn.over_sampling import SMOTE

In [21]:

# Separate features (X) and target labels (y)
X = df.drop(['Feedback', 'Text'], axis=1)  # Exclude 'Feedback' and 'Text' columns
y = df['Feedback']



In [22]:
print(X)

       00       000  000063  002  0025  003  0030  007  008   01  ...  ænnen   
0     0.0  0.163463     0.0  0.0   0.0  0.0   0.0  0.0  0.0  0.0  ...    0.0  \
1     0.0  0.000000     0.0  0.0   0.0  0.0   0.0  0.0  0.0  0.0  ...    0.0   
2     0.0  0.000000     0.0  0.0   0.0  0.0   0.0  0.0  0.0  0.0  ...    0.0   
3     0.0  0.000000     0.0  0.0   0.0  0.0   0.0  0.0  0.0  0.0  ...    0.0   
4     0.0  0.000000     0.0  0.0   0.0  0.0   0.0  0.0  0.0  0.0  ...    0.0   
...   ...       ...     ...  ...   ...  ...   ...  ...  ...  ...  ...    ...   
4840  0.0  0.000000     0.0  0.0   0.0  0.0   0.0  0.0  0.0  0.0  ...    0.0   
4841  0.0  0.000000     0.0  0.0   0.0  0.0   0.0  0.0  0.0  0.0  ...    0.0   
4842  0.0  0.000000     0.0  0.0   0.0  0.0   0.0  0.0  0.0  0.0  ...    0.0   
4843  0.0  0.000000     0.0  0.0   0.0  0.0   0.0  0.0  0.0  0.0  ...    0.0   
4844  0.0  0.000000     0.0  0.0   0.0  0.0   0.0  0.0  0.0  0.0  ...    0.0   

      ænsi  ærnits  ærtsil  ærvi  ærvin

In [23]:
# Apply SMOTE to balance the dataset
smote = SMOTE(sampling_strategy='minority')
X_resampled, y_resampled = smote.fit_resample(X, y)

In [24]:
print(y_resampled)

0       2
1       1
2       3
3       3
4       3
       ..
7114    1
7115    1
7116    1
7117    1
7118    1
Name: Feedback, Length: 7119, dtype: object


In [25]:
y_sampled_series = pd.Series(y_resampled)

# Print the value counts
print(y_sampled_series.value_counts())

Feedback
2    2878
1    2878
3    1363
Name: count, dtype: int64


Applying Machine Learning Models

In [26]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2)


In [27]:

# Find rows with NaN values
rows_with_nan = X_resampled[X_resampled.isnull().any(axis=1)]

# Remove rows with NaN values
X_resampled = X_resampled.dropna()

# You can also reset the index if needed
X_resampled.reset_index(drop=True, inplace=True)

knn

In [28]:
n_neighbors = 5  # Replace with the desired number of neighbors
knn_classifier = KNeighborsClassifier(n_neighbors=n_neighbors)

# Fit the classifier to the training data
knn_classifier.fit(X_train, y_train)

# Make predictions on the test data
y_pred = knn_classifier.predict(X_test)

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

# Print a classification report
classification_rep = classification_report(y_test, y_pred)
print("Classification Report:\n", classification_rep)

# Print a confusion matrix
confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", confusion_mat)

Accuracy: 0.51
Classification Report:
               precision    recall  f1-score   support

           1       0.46      1.00      0.63       576
           2       0.89      0.23      0.37       574
           3       0.89      0.06      0.12       274

    accuracy                           0.51      1424
   macro avg       0.75      0.43      0.37      1424
weighted avg       0.71      0.51      0.42      1424

Confusion Matrix:
 [[575   1   0]
 [440 132   2]
 [241  16  17]]


Naive Bayes

In [30]:
from sklearn.naive_bayes import MultinomialNB

In [31]:
naive_bayes = MultinomialNB()

# Fit the classifier to the training data
naive_bayes.fit(X_train, y_train)

# Make predictions on the test data
y_pred = naive_bayes.predict(X_test)

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

# Print a classification report
classification_rep = classification_report(y_test, y_pred)
print("Classification Report:\n", classification_rep)

# Print a confusion matrix
confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", confusion_mat)


Accuracy: 0.73
Classification Report:
               precision    recall  f1-score   support

           1       0.73      0.98      0.83       576
           2       0.74      0.82      0.78       574
           3       0.71      0.04      0.07       274

    accuracy                           0.73      1424
   macro avg       0.73      0.61      0.56      1424
weighted avg       0.73      0.73      0.66      1424

Confusion Matrix:
 [[562  14   0]
 [100 470   4]
 [113 151  10]]


Random Forrest

In [32]:
from sklearn.ensemble import RandomForestClassifier


In [33]:
random_forest = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the classifier to the training data
random_forest.fit(X_train, y_train)

# Make predictions on the test data
y_pred = random_forest.predict(X_test)

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

# Print a classification report
classification_rep = classification_report(y_test, y_pred)
print("Classification Report:\n", classification_rep)

# Print a confusion matrix
confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", confusion_mat)

Accuracy: 0.84
Classification Report:
               precision    recall  f1-score   support

           1       0.93      0.95      0.94       576
           2       0.76      0.95      0.84       574
           3       0.88      0.37      0.52       274

    accuracy                           0.84      1424
   macro avg       0.86      0.76      0.77      1424
weighted avg       0.85      0.84      0.82      1424

Confusion Matrix:
 [[550  25   1]
 [ 17 544  13]
 [ 25 148 101]]


Since Random Forrest has maximum accuracy we will use Random Forrest algorithm 
 